# Generated by Django 4.1.7 on 2023-03-02 15:06

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FPUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('mc_id', models.CharField(blank=True, db_column='uniqueId', default='', max_length=50)),
                ('mc_username', models.CharField(blank=True, default='', max_length=50)),
                ('dc_id', models.PositiveBigIntegerField()),
                ('dc_username', models.CharField(max_length=50)),
                ('dc_discriminator', models.CharField(max_length=4)),
                ('dc_avatar', models.CharField(max_length=100)),
                ('dc_public_flags', models.IntegerField()),
                ('dc_flags', models.IntegerField()),
                ('dc_locale', models.CharField(max_length=100)),
                ('dc_mfa_enabled', models.BooleanField()),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('whitelisted', models.BooleanField(default=False)),
                ('access_code', models.CharField(default=main.models.random_code, max_length=40)),
                ('home_world', models.CharField(blank=True, max_length=255, null=True)),
                ('home_x', models.FloatField(blank=True, null=True)),
                ('home_y', models.FloatField(blank=True, null=True)),
                ('home_z', models.FloatField(blank=True, null=True)),
                ('death_world', models.CharField(blank=True, max_length=255, null=True)),
                ('death_x', models.FloatField(blank=True, null=True)),
                ('death_y', models.FloatField(blank=True, null=True)),
                ('death_z', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fpusers',
            },
            managers=[
                ('objects', main.models.FPManager()),
            ],
        ),
    ]
