# Generated by Django 4.1.7 on 2023-03-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpuser',
            name='mc_id',
            field=models.CharField(blank=True, db_column='uniqueId', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fpuser',
            name='mc_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
